//header responsive mobile
let domEvent = document.querySelector(".icon-menu");
let header = document.querySelector(".nav-header");
let menu = document.createElement("i");
let navLogo = document.createElement("a");
let logo = document.createElement('img');
let iconLogin = document.createElement("a");
let login = document.createElement('img');
let iconSreach = document.createElement("i");
logo.src = "https://scontent.fdad3-1.fna.fbcdn.net/v/t1.6435-9/218861047_1159755994538929_5036989354039496647_n.jpg?_nc_cat=106&ccb=1-3&_nc_sid=730e14&_nc_ohc=6VF9oPuo278AX_XGQuL&tn=WhWQRQaYHSGeQ51r&_nc_ht=scontent.fdad3-1.fna&oh=c036263496e2e103c4b5f6c466e8431e&oe=612CBAEC";
login.src = "https://images.unsplash.com/photo-1627669638788-ceffe0800a94?ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwyOXx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60";
navLogo.href = "#";
menu.classList.add("fa");
menu.classList.add("fa-bars");
menu.classList.add("icon-menu");
iconSreach.classList.add("fa");
iconSreach.classList.add("fa-search");
iconSreach.classList.add("icon-search");
logo.classList.add("image-logo");
login.classList.add("image-login");
navLogo.classList.add("logo");
iconLogin.classList.add("login");
let logoHeader = document.querySelector(".logo");
let loginHeader = document.querySelector(".login");
header.appendChild(menu);
header.appendChild(navLogo);
header.appendChild(iconLogin);
navLogo.appendChild(logo);
iconLogin.appendChild(login);
header.appendChild(iconSreach);
console.log(header);
